SET SCHEMA FN3MI0700022;

CREATE OR REPLACE MODULE USER_MOD;

ALTER MODULE USER_MOD PUBLISH PROCEDURE P_VALIDATE_USER_DATA(IN U_EMAIL VARCHAR(320), IN U_USERNAME VARCHAR(10));
ALTER MODULE USER_MOD ADD PROCEDURE P_VALIDATE_USER_DATA(IN U_EMAIL VARCHAR(320), IN U_USERNAME VARCHAR(10))
BEGIN
    DECLARE UID INT;
    SET UID = (SELECT U.UID FROM FN3MI0700022.USERS U WHERE U.USERNAME = U_USERNAME OR U.EMAIL = U_EMAIL);

    IF UID IS NOT NULL
        THEN SIGNAL SQLSTATE '70001'
            SET MESSAGE_TEXT = 'Username or email is not unique!';
    END IF;
END;

CALL FN3MI0700022.USER_MOD.P_VALIDATE_USER_DATA('fakeemail1@yahoo.com', 'coolguy56');

CREATE OR REPLACE MODULE COMPANIES_MOD;

SELECT * FROM FN3MI0700022.COMPANIES C;

ALTER MODULE COMPANIES_MOD PUBLISH PROCEDURE P_GET_ALL_COMPANIES_IN_WHICH_AMATEURS_WORKS_INFO();
ALTER MODULE COMPANIES_MOD ADD PROCEDURE P_GET_ALL_COMPANIES_IN_WHICH_AMATEURS_WORKS_INFO()
BEGIN
    --DECLARE COMPANIES_CURSOR CURSOR FOR ();
END;