SET SCHEMA FN3MI0700022;

-- A trigger that validates the user data before insert.
CREATE OR REPLACE TRIGGER TRIG_BEFORE_USER_INSERT
    BEFORE INSERT ON FN3MI0700022.USERS
    REFERENCING NEW AS N
    FOR EACH ROW
    BEGIN
        DECLARE V_IS_VALID_DATA BOOLEAN;
        CALL FN3MI0700022.USER_MOD.P_VALIDATE_USER_DATA(N.EMAIL,
                                                        N.USERNAME,
                                                        V_IS_VALID_DATA);
        IF V_IS_VALID_DATA = TRUE
            THEN INSERT INTO FN3MI0700022.USERS(EMAIL, USERNAME, PASSWORD)
                 VALUES (N.EMAIL, N.USERNAME, N.PASSWORD);
        END IF;
    END;

-- A trigger that validates the user date before update.
CREATE OR REPLACE TRIGGER TRIG_BEFORE_USER_UPDATE
    BEFORE UPDATE ON FN3MI0700022.USERS
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
BEGIN
    DECLARE V_IS_VALID_DATA BOOLEAN;
    CALL FN3MI0700022.USER_MOD.P_VALIDATE_USER_DATA(N.EMAIL,
                                                    N.USERNAME,
                                                    V_IS_VALID_DATA);
    IF V_IS_VALID_DATA = TRUE THEN
        IF O.EMAIL != N.EMAIL OR O.USERNAME != N.USERNAME
               OR O.PASSWORD != N.PASSWORD
            THEN UPDATE FN3MI0700022.USERS U
                 SET U.EMAIL = N.EMAIL,
                     U.USERNAME = N.USERNAME,
                     U.PASSWORD = N.PASSWORD
                 WHERE U.UID = O.UID;
        END IF;
    END IF;
END;


-- A trigger that logs deletions from Projects table
-- (after a definite project is deleted).
CREATE TABLE DELETED_PROJECTS_LOG (
    PID INTEGER GENERATED ALWAYS AS IDENTITY
    CONSTRAINT PK_DEL_PROJECTS
    PRIMARY KEY,
    P_NAME VARCHAR(50),
    P_VERSION VARCHAR(20),
    RELEASE_DATE DATE DEFAULT CURRENT_DATE,
    P_DESCRIPTION VARCHAR(350),
    CHECK (P_VERSION LIKE '%_'),
    CHECK (RELEASE_DATE >= DATE('2023-01-01'))
);

CREATE OR REPLACE TRIGGER TRIG_LOG_AFTER_PROJECT_DELETION
    AFTER DELETE ON FN3MI0700022.PROJECTS
    REFERENCING OLD AS O
    FOR EACH ROW
BEGIN
    INSERT INTO FN3MI0700022.DELETED_PROJECTS_LOG(P_NAME, P_VERSION, P_DESCRIPTION)
        VALUES (O.P_NAME, O.P_VERSION, O.P_DESCRIPTION);
END;